### ISSUE TITLE
docs: add command documentation. 

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/savanna-bot#12]
It seems that we have not mentioned anywhere how to use the bot. It should be good to add a section in the docs to show how to use the bot and if possible, add some screenshots.

**Comment by ghost** [comment]
HOW do we use this on our discord ? should I follow the steps under configuration under readme file ?

**Comment by antonio-pedro99** [comment]
> HOW do we use this on our discord ? should I follow the steps under configuration under readme file ?

Hi @capedCrusaderr, if you want to extend its feature and then use it, you should use the instructions under the README. If you just want to use it directly, you can follow this [link](https://discord.com/api/oauth2/authorize?client_id=1138189651593674845&permissions=274877908992&scope=bot) to add it to your server.

**Comment by antonio-pedro99** [comment]
If you are interested to work on this issue, note that you will have to follow these guidelines https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

**Comment by antonio-pedro99** [comment]
@capedCrusaderr tell me if you need any help.

**Comment by ghost** [comment]
sure sure . let me first try and see how It works . then accordingly I will make a documentation .

**Comment by ghost** [comment]
Hey @antonio-pedro99 , i wanted to ask how should i draft the documentation , what should I include in it ?

**Comment by antonio-pedro99** [comment]
> Hey @antonio-pedro99 , i wanted to ask how should i draft the documentation , what should I include in it ?

I think you do not need to cover all the commands.
See, the commands are exactly equivalent to queries in GitHub, check it here: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

We only need the basics one, if the user wants more advanced thing, he can consult the above link.
Think about:
— how to search by programming language, organization, updated and created time, by labels (other than good first), by interactions, etc.

The current implementation is already checking for issues and if the issue is open.
Example of valid command is,

`/svn language:Python owner:angolaosc`
this would return all the issues(with good first issue label) from repositories where python is the predominant programming language, under angolaosc

**Comment by ghost** [comment]
thecapedcrusader5203 is my discord username , let's connect so that I can discuss regarding documentation.

**Comment by antonio-pedro99** [comment]
> thecapedcrusader5203 is my discord username , let's connect so that I can discuss regarding documentation.

I have sent an invitation.

**Comment by KelvimImperial** [comment]
Hey @antonio-pedro99

**Comment by antonio-pedro99** [comment]
@KelvimImperial vamos iniciar com este #13

**Comment by antonio-pedro99** [comment]
Hey @capedCrusaderr, any update on this?

**Comment by ghost** [comment]
Hey mate , i was just pushing the commit and there was some error, as the files were not tracked

**Comment by antonio-pedro99** [comment]
> Hey mate , i was just pushing the commit and there was some error, as the files were not tracked

Do you need any help?

**Comment by antonio-pedro99** [comment]
I think `git add <file you have changed>` might do the trick

**Comment by ghost** [comment]
I committed the changes

**Comment by ghost** [comment]
hey @antonio-pedro99 , I am trouble finding about the commands regarding the bot . Please guide me out

**Comment by antonio-pedro99** [comment]
Closed by #20
