### ISSUE TITLE
feat: Adicionar suporte para argumentos em português

### ISSUE THREAD

**Issue by antonio-pedro99** [angolaosc/savanna-bot#13]
A corrente versão do bot usa queries do Github para executar as pesquisas. Essas queries são totalmente em inglês, dificultando não falantes de português usarem o bot. 

Seria bom se o bot suportasse comandos em português, exemplo: `dono:angolaosc`, `linguagem:Python` e outros comandos. 
A ideia seria criar um mecanismo para extrair os argumentos e fazer a tradução literal em português e retornar a query equivalente em Inglês, e enviar para o `GithubSearcher.search(Str)`. 

hint: usar dicionário. 
Referência: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

**Comment by antonio-pedro99** [comment]
@KelvimImperial vamos começar com este

**Comment by antonio-pedro99** [comment]
Atualmente nós conseguimos fazer pesquisas usando queries nativa do Github search, exemplo:
`/svn language:Dart owner:angolaosc` 
A implementação do bot neste caso seria usar os argumentos:
`language:Dart owner:angolaosc` e substituir na aquisição da API do Github, a ideia é criar um mecanismo para que usuários que não falam inglês poderem usar argumentos em português como,
`/svn linguagem:Dart dono:angolosc`
Antes de fazer a aquisão, nós temos que mapear e traduzir os argumentos para Inglês e subsistituir na aquisição da API do GitHub.

Eu penso em algo como,
1. Extrair todos argumentos
2. Formar um mapa:
Um dicionário ia funcionar, um dicionário com as traduções do tipo,
```python
translations = {"linguagem": "language", "dono":"owner", "actualização": "updated": , "created": "criado"}
```
ao receber argumentos como `/svn linguagem:Dart dono:google` por exemplo, a query para enviar na aquisição seria,
`q = language:Dart owner:google`

**Comment by KelvimImperial** [comment]
Está bem

**Comment by matiasdev30** [comment]
@antonio-pedro99  fiz o fork agora mais, posso trabalhar nessa issue ou posso pegar uma outra?

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 fiz o fork agora mais, posso trabalhar nessa issue ou posso pegar uma outra?

@KelvimImperial vais pegar a issue ou o @matiasdev30 pode pegar?

**Comment by antonio-pedro99** [comment]
@matiasdev30 podes dar uma olhada nesta #17

**Comment by matiasdev30** [comment]
OK @antonio-pedro99 tomei nota, precisarei só do teu suporte lá na discussão

**Comment by antonio-pedro99** [comment]
> OK @antonio-pedro99 tomei nota, precisarei só do teu suporte lá na discussão

Estou à disposição

**Comment by antonio-pedro99** [comment]
@KelvimImperial como estás mano?
Ainda continuas a trabalhar nessa cena_

**Comment by jocaetano1** [comment]
Olá,  @antonio-pedro99.

Gostaria adicionar essa feature ao savanna-bot.

**Comment by antonio-pedro99** [comment]
> Olá, @antonio-pedro99.
> 
> Gostaria adicionar essa feature ao savanna-bot.

Com certeza.

**Comment by jocaetano1** [comment]
Boas obrigado.
